export const AUTHENTICATION_PASS = 'AUTHENTICATION_PASS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';

export const VERIFICATION_FAIL = 'VERIFICATION_FAIL';

export const LOGIN_PASS = 'LOGIN_PASS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';